"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const body_parser_1 = __importDefault(require("body-parser"));
const auth_1 = __importDefault(require("../routes/auth"));
const user_1 = __importDefault(require("../routes/user"));
const transmission_1 = __importDefault(require("../routes/transmission"));
const orderRelease_1 = __importDefault(require("../routes/orderRelease"));
const error_1 = __importDefault(require("../middleware/error"));
const schemaItem_1 = __importDefault(require("../routes/schemaItem"));
const schemaRelease_1 = __importDefault(require("../routes/schemaRelease"));
const item_1 = __importDefault(require("../routes/item"));
const location_1 = __importDefault(require("../routes/location"));
const schemaLocation_1 = __importDefault(require("../routes/schemaLocation"));
const party_1 = __importDefault(require("../routes/party"));
const schemaParty_1 = __importDefault(require("../routes/schemaParty"));
const transaction_1 = __importDefault(require("../routes/transaction"));
const schemaTransaction_1 = __importDefault(require("../routes/schemaTransaction"));
const orderBase_1 = __importDefault(require("../routes/orderBase"));
const schemaOrderBase_1 = __importDefault(require("../routes/schemaOrderBase"));
const audit_1 = __importDefault(require("../routes/audit"));
const setting_1 = __importDefault(require("../routes/setting"));
const trackingEvent_1 = __importDefault(require("../routes/trackingEvent"));
const schemaTrackingEvent_1 = __importDefault(require("../routes/schemaTrackingEvent"));
const shipment_1 = __importDefault(require("../routes/shipment"));
const schemaShipment_1 = __importDefault(require("../routes/schemaShipment"));
const bom_1 = __importDefault(require("../routes/bom"));
const schemaBom_1 = __importDefault(require("../routes/schemaBom"));
function default_1(app) {
    app.use(body_parser_1.default.json({ limit: '50mb' }));
    app.use(body_parser_1.default.urlencoded({ limit: '50mb', extended: true }));
    app.use('/api/auth', auth_1.default);
    app.use('/api/user', user_1.default);
    app.use('/api/audit', audit_1.default);
    app.use('/api/item', item_1.default);
    app.use('/api/order-release', orderRelease_1.default);
    app.use('/api/location', location_1.default);
    app.use('/api/party', party_1.default);
    app.use('/api/bom', bom_1.default);
    app.use('/api/transaction', transaction_1.default);
    app.use('/api/order-base', orderBase_1.default);
    app.use('/api/tracking-event', trackingEvent_1.default);
    app.use('/api/shipment', shipment_1.default);
    app.use('/api/schema/item', schemaItem_1.default);
    app.use('/api/schema/order-release', schemaRelease_1.default);
    app.use('/api/schema/location', schemaLocation_1.default);
    app.use('/api/schema/party', schemaParty_1.default);
    app.use('/api/schema/bom', schemaBom_1.default);
    app.use('/api/schema/transaction', schemaTransaction_1.default);
    app.use('/api/schema/order-base', schemaOrderBase_1.default);
    app.use('/api/schema/tracking-event', schemaTrackingEvent_1.default);
    app.use('/api/schema/shipment', schemaShipment_1.default);
    app.use('/api/transmission', transmission_1.default);
    app.use('/api/settings', setting_1.default);
    app.use(error_1.default);
}
exports.default = default_1;
